### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '_categories/Cardiovascular_Health.html'

### ISSUE THREAD

**Issue by Stephenitis** [NoTranslationLayer/biomarkerdash#17]
neat project, rip wellnessfx.

ran into this error while trying to build

```
Plot for Fibrinogen saved to /Users/eeveehome/biomarkerdash/_includes/Fibrinogen.html.
Traceback (most recent call last):
  File "/Users/eeveehome/biomarkerdash/scripts/./load_wellnessfx.py", line 100, in <module>
    output_file = htm.combine_html_files(category, html_content)
  File "/Users/eeveehome/miniforge3/lib/python3.10/site-packages/biomarkerdash/html.py", line 68, in combine_html_files
    with open(output_path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '_categories/Cardiovascular_Health.html'
```
My CSV looks like this
![Monosnap 2023-08-23 14-55-36](https://github.com/NoTranslationLayer/biomarkerdash/assets/1712162/bc734164-86ad-4846-ad50-c4a51b6acbd7)

**Comment by sstarcher** [comment]
Same issue as above
```
Traceback (most recent call last):
  File "./load_wellnessfx.py", line 100, in <module>
    output_file = htm.combine_html_files(category, html_content)
  File "/Users/x.x/.pyenv/versions/3.7.4/lib/python3.7/site-packages/biomarkerdash/html.py", line 68, in combine_html_files
    with open(output_path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '_categories/Cardiovascular_Health.html'
```

**Comment by brianbohanon** [comment]
Same issue as above. I did notice that the entire _categories folder is empty after building. Thanks for putting this together, looks like a nice replacement to WellnessFX.

**Comment by ddn** [comment]
I fixed this by hardcoding the entire path to the _categories directory.

Line 43:

`output_directory: str = "/home/user/biomarkerdash/_categories",`

**Comment by ddn** [comment]
You can fix this easily by changing the code or simply changing how you call it, i.e.:

For example, calling it from the parent directory instead of from scripts/ fixes it:

`./scripts/load_wellnessfx.py test_result_export.csv`

The only catch is that if you try to load the HTML output from a web server the paths will be messed up because they're absolute filesystem paths. This is easy to fix with a search and replace, or could be fixed in the code by someone less lazy than I.

**Comment by 5yler** [comment]
Thanks @Stephenitis @sstarcher @brianbohanon @ddn for bringing this to our attention - the issue should be resolved now with both updated README and making the behavior of the script invariant to the directory where it's called from.
